### ISSUE TITLE
Verizion Report

### ISSUE THREAD

**Issue by idev** [jacobdjwilson/awesome-annual-security-reports#16]
Hello,

should i also open a pull request for the Verizion Report:
https://www.verizon.com/business/resources/reports/2024-dbir-data-breach-investigations-report.pdf

Problem, it is behind a "Registration From" :( 

Kind regards

**Comment by jacobdjwilson** [comment]
Hi! The 2024 DBIR report should be in the repository already. Thanks!

https://github.com/jacobdjwilson/awesome-annual-security-reports/blob/main/Annual%20Security%20Reports/2024/Verizon-Data-Breach-Investigations-Report-2024.pdf
