### ISSUE TITLE
2024 Missing Reports

### ISSUE THREAD

**Issue by luv2dnce33** [jacobdjwilson/awesome-annual-security-reports#9]
Hi thanks for maintaining this repository. Your project is pioneering a pretty critical service to industry professionals in essentially creating a timeline of the threat landscape at large.

However, I am curious how three of the highest fidelity and arguably the most objective industry proven, actionable, and technical reports such as: [RedCanary](https://redcanary.com/threat-detection-report/), [Blackpoint](https://blackpointcyber.com/resources/cybersecurity-annual-threat-report-2024/), and [Huntress](https://www.huntress.com/resources/smb-threat-report) amongst some others are being missed?

Is it lack of awareness, care, etc? Anything the community can do to assist? It is a fantastic idea and has the potential to really be high value but oversights such as these are concerning as an observer and professional who uses such reports to generate signals, trends, and collect data as opposed to your average reader looking to consume.

**Comment by jacobdjwilson** [comment]
Yep I can work on that, or you can feel free to issue a PR and I can merge.

**Comment by jacobdjwilson** [comment]
@ank0ku I was unable to gather the Huntress report linked in this issue, but I have uploaded the other reports. Just waiting to update the readme once all three have been gathered. If you are able to gather the final report it would be very helpful.

**Comment by jacobdjwilson** [comment]
All 3 reports noted in original issue have been added.
